export const FETCH_CUSTOMERS_START = 'FETCH_CUSTOMERS_START';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_ERROR = 'FETCH_CUSTOMERS_ERROR';
export const SET_CURRENT_CUSTOMER = 'SET_CURRENT_CUSTOMER';
export const TOGGLE_CUSTOMER_CHANGE = 'TOGGLE_CUSTOMER_CHANGE';