// Customer
export const TOGGLE_SHOW_NEW_CUSTOMER_MODAL = 'TOGGLE_SHOW_NEW_CUSTOMER_MODAL';

export const POST_CUSTOMER_SUCCESS = 'POST_CUSTOMER_SUCCESS';
export const POST_CUSTOMER_ERROR = 'POST_CUSTOMER_ERROR';

export const GET_ALL_CUSTOMERS_SUCCESS = 'GET_ALL_CUSTOMERS_SUCCESS';
export const GET_ALL_CUSTOMERS_ERROR = 'GET_ALL_CUSTOMERS_ERROR';

export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_ERROR = 'GET_CUSTOMER_ERROR';





// Project
export const TOGGLE_SHOW_TIME_TRACK_MODAL = 'TOGGLE_SHOW_TIME_TRACK_MODAL';
export const TOGGLE_SHOW_NEW_PROJECT_MODAL = 'TOGGLE_SHOW_NEW_PROJECT_MODAL';
export const SET_PROJECT_WORKING_TIME = 'SET_PROJECT_WORKING_TIME';

export const POST_PROJECT_SUCCESS = 'POST_PROJECT_SUCCESS';
export const POST_PROJECT_ERROR = 'POST_PROJECT_ERROR';

export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECT_SUCCESS';
export const GET_ALL_PROJECTS_ERROR = 'GET_ALL_PROJECT_ERROR';

export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_ERROR = 'GET_PROJECT_ERROR';




// Authorization
export const TOGGLE_LOGIN = 'TOGGLE_LOGIN';

// General
export const START_LOADING = 'START_LOADING';



