// Customer
export const FETCH_CUSTOMERS_START = 'FETCH_CUSTOMERS_START';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_ERROR = 'FETCH_CUSTOMERS_ERROR';
export const SET_CURRENT_CUSTOMER = 'SET_CURRENT_CUSTOMER';
export const TOGGLE_CUSTOMER_CHANGE = 'TOGGLE_CUSTOMER_CHANGE';

// Project
export const FETCH_PROJECTS_START = 'FETCH_PROJECTS_START';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_ERROR = 'FETCH_PROJECTS_ERROR';

export const SET_PROJECT_WORKING_TIME = 'SET_PROJECT_WORKING_TIME';
export const TOGGLE_SHOW_TIME_TRACK_MODAL = 'TOGGLE_SHOW_TIME_TRACK_MODAL';
export const SET_PROJECT_NOTES = 'SET_PROJECT_NOTES';

